#      ___           ___   
#     /__/\         /  /\  
#     \  \:\       /  /:/_ 
#      \  \:\     /  /:/ /\
#  _____\__\:\   /  /:/ /:/
# /__/::::::::\ /__/:/ /:/ 
# \  \:\~~\~~\/ \  \:\/:/  
#  \  \:\  ~~~   \  \::/   
#   \  \:\        \  \:\   
#    \  \:\        \  \:\  
#     \__\/         \__\/
#     
#

# Welcome to the NF example docker-compose.  This file should stand up
# a mostly functioning NF instance on your desktop.  Before running
# you should just check a few things:
#  1. several containers need a writable volume, which this file puts in /tmp by default
#  2. if the BACnet service fails to start, you may need to specify
#   which interface to use in its environment.

version: "2.2"
services:

  # this is the load balancer through which you access all APIs and the console.
  # See envoy.yaml in this conf as a starting point to adapt to your
  #  own configuration.
  envoy:
    image: normalframework/envoy:release
    env_file: .env.dev
    networks:
      - internal
    ports:
      - "8080:8080"    

  # Most persistent data is in redis.  This is essentially an
  #  unmodified upstream with RediSearch and RedisTimeseries installed.
  redis:
    image: normalframework/redis:release
    networks:
      - internal

    # Set this to a directory where the redis backing store can be written
    volumes:
        - /tmp/devdata:/data
    
  # Static nginx server with the console web assets.
  admin-static:
    image: normalframework/nf-console:release
    networks:
      - internal
    depends_on:
      - redis
    
  # BACnet service.  Unlike the the other services, this must run in
  #  network host mode; otherwise UDP broadcast works badly for discovery.  
  bacnet-service:
    image: normalframework/nf:release
    env_file: .env.dev
    command: nf bacnet-hpl  #-memprofile mem.prof
    # provide a volume here to persist bacnet settings
    volumes:
      - /tmp/nf-bacnet/:/etc/bacnet/

    depends_on:
      - redis
    networks:
      - internal

  bacnet-simulator:
    image: stevedh/bactools
    command: server
    
    networks:
      - internal
    environment:
      - BACNET_IP_DEBUG=1
    
  # Service that manages scanning the local network for BACnet devices
  scan-service:
    image: normalframework/nf:release
    env_file: .env.dev
    command: nf bacnet-scan
    networks:
      - internal
    depends_on:
      - redis
      - point-service
    
  # Service that collects data by polling configured points.
  poll-service:
    image: normalframework/nf:release
    env_file: .env.dev
    command: nf bacnet-poll 
    networks:
      - internal
    depends_on:
      - redis
      - point-service
    
  # the points database
  point-service:
    image: normalframework/nf:release
    env_file: .env.dev
    command: nf point
    networks:
      - internal
    depends_on:
      - redis
    ports:
      - "9093:9093"
    # set these to a directory which can be used to store pending data
    volumes:
      - /tmp/nf-spool-data:/data
      - /tmp/nfs-spool-errors:/errors

    environment:
      - DATA_LOG_DIR=/data
      - ERROR_LOG_DIR=/errors

  # Tracks the state of devices in the network
  bacnet-status-service:
    image: normalframework/nf:release
    env_file: .env.dev
    command: nf hpl-status
    networks:
      - internal


  # Create sparkplug services to send data out using MQTT
  #  See the configuration guide on docs.normal.dev for example setup.
#  sparkplug-service:
#    image: normalframework/nf:release
#    env_file: .env.dev
##    command: nf sparkplug
#    networks:
#      - internal
#    environment:
#      - MQTT_BROKER=localhost
#    


networks:
  # the services all talk on this network which is only exposed through envoy
  internal:
