#      ___           ___   
#     /__/\         /  /\  
#     \  \:\       /  /:/_ 
#      \  \:\     /  /:/ /\
#  _____\__\:\   /  /:/ /:/
# /__/::::::::\ /__/:/ /:/ 
# \  \:\~~\~~\/ \  \:\/:/  
#  \  \:\  ~~~   \  \::/   
#   \  \:\        \  \:\   
#    \  \:\        \  \:\  
#     \__\/         \__\/
#     
#

# Welcome to the NF example docker-compose.  This file should stand up
# a mostly functioning NF instance on your desktop.  Before running
# you should just check a few things:
#  1. several containers need a writable volume, which this file puts in /tmp by default
#  2. if the BACnet service fails to start, you may need to specify
#   which interface to use in its environment.
#
# This compose file runs entirely in a docker internal network, along
# with a simple BACnet simulator.

version: "2.2"
services:

  # the main container which runs all the NF services, load balancer,
  # and management console.
  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:1.5
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - redis
    read_only: true
    tmpfs:
      - /run:exec
      - /etc/nginx/conf.d/
    ports:
      - "8080:8080"
    environment:
      - S6_READ_ONLY_ROOT=1 
      - REDIS_ADDRESS=redis:6379
      
#  if you want data to be persistent, you need to mount /var in the container
#  a volume
    volumes:
      - /tmp/nf:/var

  # Most persistent data is in redis.  This is essentially an
  #  unmodified upstream with RediSearch and RedisTimeseries installed.
  redis:
    image: normalframework.azurecr.io/normalframework/redis:1.5
    networks:
      - internal
    read_only: true
    volumes:
      - /tmp/nf-redis:/data

  bacnet-simulator:
    image: stevedh/bactools
    command: server
    
    networks:
      - internal
    environment:
      - BACNET_IP_DEBUG=1
      
networks:
  internal:
  
